// Données initiales issues du carnet de voyage (66 idées).
export const SEED = {
 "trip": {
  "title": "Corée du Sud",
  "korean": "대한민국",
  "dates": "24 sept → 10 oct 2026",
  "nights": 16,
  "segments": [
   {
    "city": "Séoul",
    "nights": 3,
    "dates": "24–27 sept"
   },
   {
    "city": "Jeju",
    "nights": 3,
    "dates": "27–30 sept"
   },
   {
    "city": "Busan",
    "nights": 4,
    "dates": "30 sept – 4 oct"
   },
   {
    "city": "Jeonju",
    "nights": 2,
    "dates": "4–6 oct"
   },
   {
    "city": "Séoul",
    "nights": 4,
    "dates": "6–10 oct"
   }
  ]
 },
 "cities": [
  {
   "id": "seoul",
   "label": "Séoul",
   "korean": "서울",
   "note": "2 séjours · 7 nuits"
  },
  {
   "id": "jeju",
   "label": "Jeju",
   "korean": "제주",
   "note": "3 nuits"
  },
  {
   "id": "busan",
   "label": "Busan",
   "korean": "부산",
   "note": "4 nuits"
  },
  {
   "id": "gyeongju",
   "label": "Gyeongju",
   "korean": "경주",
   "note": "Day trip depuis Busan"
  },
  {
   "id": "jeonju",
   "label": "Jeonju",
   "korean": "전주",
   "note": "2 nuits"
  }
 ],
 "ideas": [
  {
   "id": "seoul-city-wall",
   "city": "seoul",
   "title": "Seoul City Wall",
   "kr": "한양도성 · Hanyangdoseong",
   "type": "Activité · Rando urbaine",
   "verdict": "oui",
   "note": "Section à arbitrer à J-30 — options gardées ouvertes",
   "desc": "Mur d'enceinte du XIVᵉ siècle qui ceinturait l'ancienne capitale Hanyang, sur 18,6 km à travers 4 montagnes autour de Séoul.",
   "zone": "Plusieurs points d'accès dans Séoul",
   "avis": "Un des trucs les plus uniques de Séoul, sous-coté face aux spots plus 'Instagram'.",
   "when": "Plutôt séjour 2 (6–10 oct)",
   "origin": "carnet",
   "lat": 37.5779633,
   "lng": 127.0084459
  },
  {
   "id": "pc-bang",
   "city": "seoul",
   "title": "PC Bang",
   "kr": "피시방 · Soirée gaming café",
   "type": "Soirée · Expérience culturelle",
   "verdict": "oui",
   "note": "Win facile — pas cher, sans prise de tête, très local",
   "desc": "Les gaming cafés ouverts 24/7 qui sont une véritable institution coréenne.",
   "zone": "Hongdae · Gangnam · Sinchon",
   "avis": "Vraiment chouette comme plan soir si on aime jouer, même 1h.",
   "when": "Plan soir flexible · idéal après un dîner à Hongdae",
   "origin": "carnet",
   "lat": 37.5561973,
   "lng": 126.9250341
  },
  {
   "id": "moony-music-box",
   "city": "seoul",
   "title": "Moony Music Box",
   "kr": "무늬공방 · Atelier DIY de boîtes à musique",
   "type": "Atelier · Souvenir personnalisé",
   "verdict": "oui",
   "note": "Le souvenir intelligent — unique, personnel, BTS-friendly",
   "desc": "Atelier d'artisans en plein cœur d'Insadong (centre commercial Ssamzigil) où tu fabriques ta propre boîte à musique personnalisée.",
   "zone": "Insadong (Jongno-gu) · centre commercial Ssamzigil, 1er étage",
   "avis": "Parmi tous les souvenirs touristiques de Corée, c'est probablement le plus malin.",
   "when": "Idéal séjour 1 ou 2 · une matinée/après-midi à Insadong + Bukchon",
   "origin": "carnet",
   "lat": 37.5741603,
   "lng": 126.9848384
  },
  {
   "id": "slow-bread",
   "city": "seoul",
   "title": "Slow Bread",
   "kr": "슬로우브레드 · Boulangerie artisanale",
   "type": "Boulangerie · Café / brunch",
   "verdict": "oui",
   "note": "Pain artisanal de qualité — à caler en brunch ou pause balade",
   "desc": "Boulangerie artisanale dans la mouvance de la 'slow bread' coréenne : pains au levain naturel, farines de qualité, formats bistrot/européens loin des viennoiseries ultra-sucrées qui dominent en Corée.",
   "zone": "À confirmer — 2 'Slow Bread' à Séoul (voir options)",
   "avis": "Bon choix pour casser la routine sucrée des cafés instagrammables — ici c'est du vrai pain de boulanger, pas du fluffy garni.",
   "when": "À caler selon le quartier choisi à J-30",
   "origin": "carnet"
  },
  {
   "id": "ghibli-exhibition-jeju",
   "city": "jeju",
   "title": "Studio Ghibli Exhibition",
   "kr": "스튜디오 지브리展 · Première expo officielle en Corée",
   "type": "Exposition · Immersif",
   "verdict": "oui",
   "note": "Ouverture toute récente (11 juillet 2026) — premier du genre en Corée",
   "desc": "Première exposition officielle originale du Studio Ghibli en Corée du Sud, ouverte le 11 juillet 2026 au Donghwa Art Center (Songdang, Gujwa-eup).",
   "zone": "Songdang, Gujwa-eup, Jeju-si (est de l'île) · 1183 Bijarim-ro",
   "avis": "Ça vient littéralement d'ouvrir, donc c'est frais et probablement pas encore blindé comme ça le sera dans 6 mois.",
   "when": "Séjour Jeju (27–30 sept) · prévoir une demi-journée est de l'île",
   "origin": "carnet",
   "lat": 33.4370803,
   "lng": 126.7309273
  },
  {
   "id": "ddp-beauty-translated",
   "city": "seoul",
   "title": "DDP — Beauty, Translated",
   "kr": "동대문디자인플라자 · Expo K-beauty",
   "type": "Exposition · Gratuit",
   "verdict": "oui",
   "note": "Se termine le 27 septembre — à caser vite, en tout début de séjour",
   "desc": "Exposition gratuite au Dongdaemun Design Plaza autour de la K-beauty : diagnostic peau/cheveux assisté par technologie, essayage maquillage virtuel, présentation de marques coréennes.",
   "zone": "Dongdaemun (DDP)",
   "avis": "Bon point d'entrée si vous atterrissez le 24 — mais la fenêtre est courte (fin le 27), donc à ne pas remettre à plus tard sous peine de la rater complètement.",
   "when": "24 ou 27 sept (avant Jeju)",
   "origin": "carnet",
   "lat": 37.5665256,
   "lng": 127.0092236
  },
  {
   "id": "euljiro",
   "city": "seoul",
   "title": "Euljiro",
   "kr": "을지로 · Quartier ateliers/bars",
   "type": "Quartier · Balade nocturne",
   "verdict": "oui",
   "note": "Idéal pour errer sans itinéraire fixe",
   "desc": "Mélange singulier d'ateliers industriels anciens, de petits commerces et de nouveaux bars cachés sous des enseignes vieillottes et dans des immeubles décrépis.",
   "zone": "Jung-gu, entre Euljiro 1-ga et 3-ga",
   "avis": "Se prête très bien à une approche 'entrer dans les recoins plutôt que suivre le guide' — parfait en fin de journée sans réservation, dîner + bar selon l'inspiration du moment.",
   "when": "Soir d'arrivée (24 sept) après le DDP",
   "origin": "carnet",
   "lat": 37.5660286,
   "lng": 126.9954924
  },
  {
   "id": "gyeongbokgung",
   "city": "seoul",
   "title": "Gyeongbokgung",
   "kr": "경복궁 · Palais principal",
   "type": "Palais · Incontournable",
   "verdict": "oui",
   "note": "Touristique, mais assumé — vue l'intérêt pour l'histoire coréenne",
   "desc": "Le plus grand et plus emblématique des 5 palais royaux de Séoul.",
   "zone": "Jongno-gu",
   "avis": "Oui c'est LE spot touristique par excellence, mais pour quelqu'un avec un vrai intérêt pour l'histoire coréenne, l'éviter par principe n'a pas de sens.",
   "when": "25 sept, matin (jour de Chuseok — cérémonie de la garde royale gratuite)",
   "origin": "carnet",
   "lat": 37.579617,
   "lng": 126.977041
  },
  {
   "id": "seochon-suseongdong",
   "city": "seoul",
   "title": "Seochon + Suseongdong Valley",
   "kr": "서촌 · Ruelles + vallée",
   "type": "Quartier · Nature urbaine",
   "verdict": "oui",
   "note": "Tongin Market en bonus seulement — risque de fermeture pendant Chuseok",
   "desc": "Quartier tranquille à l'ouest de Gyeongbokgung : ruelles calmes, petits commerces, ambiance résidentielle.",
   "zone": "Ouest de Gyeongbokgung, Jongno-gu",
   "avis": "Le genre de quartier qui se prête à l'errance sans plan précis.",
   "when": "25 sept, après-midi (après Gyeongbokgung)",
   "origin": "carnet",
   "lat": 37.582128,
   "lng": 126.964323
  },
  {
   "id": "deoksugung-night",
   "city": "seoul",
   "title": "Deoksugung de nuit",
   "kr": "덕수궁 · Palais illuminé",
   "type": "Palais · Soir",
   "verdict": "oui",
   "note": "Ouvert jusqu'à 21h — contraste fort avec Gyeongbokgung le matin",
   "desc": "Palais royal ouvert en nocturne jusqu'à 21h (dernière entrée 20h) — l'un des rares avec cette option.",
   "zone": "Jung-gu, à côté de City Hall",
   "avis": "Faire Gyeongbokgung en pleine journée puis Deoksugung illuminé le soir donne deux expériences de palais totalement différentes en une seule journée — plus marquant qu'une montée à la N Seoul Tower.",
   "when": "25 sept, soir",
   "origin": "carnet",
   "lat": 37.5658862,
   "lng": 126.9749017
  },
  {
   "id": "changdeokgung-huwon",
   "city": "seoul",
   "title": "Changdeokgung + Huwon (Jardin secret)",
   "kr": "창덕궁 후원 · Jardin royal",
   "type": "Palais · Réservation requise",
   "verdict": "oui",
   "note": "RÉSERVATION CRITIQUE — vente en ligne ouverte 6 jours avant à 10h (heure Corée)",
   "desc": "Le Secret Garden (Huwon) de Changdeokgung est un jardin royal boisé avec étangs et pavillons, dans un cadre bien plus naturel que les cours pavées des autres palais.",
   "zone": "Jongno-gu, station Anguk",
   "avis": "Le vrai plus par rapport à 'encore un palais' : on marche dans les reliefs, les arbres et les étangs plutôt que sur des cours pavées.",
   "when": "26 sept, matin — réserver dès l'ouverture des ventes",
   "origin": "carnet",
   "lat": 37.5821721,
   "lng": 126.9931659
  },
  {
   "id": "bukchon-hanok-village",
   "city": "seoul",
   "title": "Bukchon Hanok Village",
   "kr": "북촌한옥마을 · Village de hanok",
   "type": "Quartier · Patrimoine",
   "verdict": "oui",
   "note": "Accès touristique limité à 10h-17h — zone résidentielle réglementée",
   "desc": "Quartier de maisons traditionnelles hanok toujours habitées, entre Gyeongbokgung et Changdeokgung.",
   "zone": "Jongno-gu, entre les deux palais",
   "avis": "Voir les rues célèbres puis bifurquer immédiatement dans les petites transversales — la foule sur une rue précise n'a aucune importance si on trouve sa propre balade 80 mètres plus loin.",
   "when": "26 sept, après-midi (14h-17h, après Huwon)",
   "origin": "carnet",
   "lat": 37.5814696,
   "lng": 126.9849519
  },
  {
   "id": "ikseon-dong",
   "city": "seoul",
   "title": "Ikseon-dong",
   "kr": "익선동 · Ruelles hanok cafés",
   "type": "Quartier · Café / dîner",
   "verdict": "oui",
   "note": "Prévoir large — pas juste un passage de 30 min",
   "desc": "Réseau dense de ruelles étroites bordées de hanok reconvertis en cafés, restaurants et petites boutiques.",
   "zone": "Jongno-gu, près d'Insadong",
   "avis": "Malgré la foule, le maillage de ruelles se prête bien à une exploration lente : dîner, dessert, éventuellement une arcade si l'envie vient.",
   "when": "26 sept, fin d'après-midi/soirée (après Bukchon)",
   "origin": "carnet",
   "lat": 37.5743484,
   "lng": 126.9897057
  },
  {
   "id": "namsan-trails",
   "city": "seoul",
   "title": "Namsan (sentiers, pas la tour)",
   "kr": "남산 · Réseau de sentiers",
   "type": "Nature urbaine · Balade",
   "verdict": "oui",
   "note": "Alternative à la montée touristique de la N Seoul Tower",
   "desc": "Namsan possède tout un réseau de sentiers de marche autour de la montagne, loin de la foule de la tour elle-même.",
   "zone": "Jung-gu / Yongsan-gu",
   "avis": "Comme matinée joker avant un vol ou un train, une petite marche sur les sentiers vaut largement mieux que la queue à l'observatoire — plus calme, gratuit, et ça reste une belle vue sur la ville.",
   "when": "27 sept matin (avant Jeju) ou 10 oct (dernier jour)",
   "origin": "carnet",
   "lat": 37.5532916,
   "lng": 126.9845912
  },
  {
   "id": "myeongdong",
   "city": "seoul",
   "title": "Myeong-dong",
   "kr": "명동 · Shopping K-beauty",
   "type": "Shopping · Quartier central",
   "verdict": "oui",
   "note": "Bon plan B si BEAUTY, TRANSLATED est raté le 24",
   "desc": "Quartier commerçant central, dense en enseignes K-beauty, mode et street food.",
   "zone": "Jung-gu",
   "avis": "Rien d'original, mais fonctionnel : shopping K-beauty rapide, street food en marchant.",
   "when": "27 sept matin ou 10 oct (jokers)",
   "origin": "carnet",
   "lat": 37.56,
   "lng": 126.9858296
  },
  {
   "id": "mangwon-market",
   "city": "seoul",
   "title": "Mangwon Market",
   "kr": "망원시장 · Marché traditionnel",
   "type": "Marché · Street food",
   "verdict": "oui",
   "note": "À faire en plus de Gwangjang, pas à la place — expériences différentes",
   "desc": "Marché de quartier traditionnel, vieux de plusieurs décennies, orienté nourriture abordable et picorage.",
   "zone": "Mapo-gu (Mangwon-dong)",
   "avis": "Bon point de départ pour une journée 'Séoul du quotidien' — moins spectaculaire que Gwangjang mais plus authentique dans l'usage.",
   "when": "6 oct, matin/midi (retour de Jeonju)",
   "origin": "carnet",
   "lat": 37.5559018,
   "lng": 126.9062854
  },
  {
   "id": "yeonnam-gyeongui-forest",
   "city": "seoul",
   "title": "Yeonnam-dong + Gyeongui Line Forest Park",
   "kr": "연남동 · 경의선숲길",
   "type": "Quartier · Parc linéaire",
   "verdict": "oui",
   "note": "Bonne transition calme avant Hongdae",
   "desc": "Parc linéaire aménagé sur une ancienne voie ferrée, traversant Mapo-gu.",
   "zone": "Mapo-gu",
   "avis": "Le contraste progressif Yeonnam (calme) → Hongdae (dense, jeune, bruyant) fonctionne bien comme arc de journée — pas besoin de choisir entre les deux ambiances, l'un mène naturellement à l'autre.",
   "when": "6 oct, après-midi (après Mangwon)",
   "origin": "carnet",
   "lat": 37.5662075,
   "lng": 126.9192364
  },
  {
   "id": "hongdae-district",
   "city": "seoul",
   "title": "Hongdae (quartier)",
   "kr": "홍대 · Pop culture / K-pop",
   "type": "Quartier · Vie nocturne",
   "verdict": "oui",
   "note": "S'enchaîne bien avec un PC bang le soir (déjà dans la liste)",
   "desc": "Pôle majeur de la culture jeune et K-pop à Séoul : boutiques de merch, figurines, arcades, rues animées.",
   "zone": "Mapo-gu",
   "avis": "Pas de raison d'éviter la foule ici — c'est le but.",
   "when": "6 oct, soir (avec le PC bang déjà prévu)",
   "origin": "carnet",
   "lat": 37.5561973,
   "lng": 126.9250341
  },
  {
   "id": "jongmyo-royal-festival",
   "city": "seoul",
   "title": "Jongmyo + K-Royal Culture Festival",
   "kr": "종묘 · Festival royal d'automne",
   "type": "Site UNESCO · Festival",
   "verdict": "option",
   "note": "Programme détaillé 2026 pas encore publié — à vérifier avant de fixer l'horaire",
   "desc": "Sanctuaire royal confucéen (UNESCO), normalement visitable uniquement en visite guidée à horaires fixes certains jours.",
   "zone": "Jongno-gu",
   "avis": "Les dates du festival sont confirmées mais pas encore le contenu précis.",
   "when": "7 oct — à confirmer selon programme du festival",
   "origin": "carnet",
   "lat": 37.5746313,
   "lng": 126.9938158
  },
  {
   "id": "changgyeonggung",
   "city": "seoul",
   "title": "Changgyeonggung",
   "kr": "창경궁 · Palais moins touristique",
   "type": "Palais",
   "verdict": "oui",
   "note": "Bon complément à Jongmyo le même jour",
   "desc": "Palais royal souvent moins fréquenté que Gyeongbokgung ou Changdeokgung, avec un jardin botanique historique.",
   "zone": "Jongno-gu, à côté de Changdeokgung",
   "avis": "Bon calme comparé aux grands palais — à combiner avec Jongmyo pour une matinée patrimoine sans trop de foule.",
   "when": "7 oct, matin (avec Jongmyo)",
   "origin": "carnet",
   "lat": 37.5788149,
   "lng": 126.9949298
  },
  {
   "id": "gwangjang-market",
   "city": "seoul",
   "title": "Gwangjang Market",
   "kr": "광장시장 · Marché historique",
   "type": "Marché · Street food",
   "verdict": "oui",
   "note": "Différent de Mangwon — faire les deux, pas l'un à la place de l'autre",
   "desc": "L'un des plus anciens marchés couverts de Séoul, réputé pour le bindaetteok (galette de haricots mungo), le mayak gimbap et une ambiance de street food dense et touristique.",
   "zone": "Jongno-gu",
   "avis": "Plus touristique et spectaculaire que Mangwon, mais ça reste un classique qui mérite sa place — les deux marchés racontent une histoire différente de la nourriture de rue coréenne.",
   "when": "7 oct, après-midi/soir",
   "origin": "carnet",
   "lat": 37.5700385,
   "lng": 126.9996038
  },
  {
   "id": "eunpyeong-jingwansa",
   "city": "seoul",
   "title": "Eunpyeong Hanok Village + Jingwansa",
   "kr": "은평한옥마을 · 진관사 · Temple + nature",
   "type": "Village + Temple · Nature",
   "verdict": "oui",
   "note": "La journée 'respiration nature' du séjour",
   "desc": "Eunpyeong Hanok Village est un quartier contemporain construit en style hanok (pas un village Joseon d'origine, à ne pas confondre avec Bukchon).",
   "zone": "Eunpyeong-gu, nord de Séoul",
   "avis": "Le meilleur candidat du séjour pour une vraie respiration nature — sans ambition de randonnée sportive : village, ruelles, temple, sentier, forêt, puis demi-tour quand l'envie s'arrête.",
   "when": "8 oct, journée",
   "origin": "carnet",
   "lat": 37.6413191,
   "lng": 126.939204
  },
  {
   "id": "mullae-art-village",
   "city": "seoul",
   "title": "Mullae Art Village",
   "kr": "문래창작촌 · Quartier industriel/artistes",
   "type": "Quartier · Optionnel",
   "verdict": "option",
   "note": "Optionnel — seulement si encore de l'énergie après Eunpyeong/Jingwansa",
   "desc": "Ancien quartier d'ateliers industriels métallurgiques où coexistent aujourd'hui artistes, petites galeries et nouveaux bars/cafés installés au milieu des ateliers encore actifs.",
   "zone": "Yeongdeungpo-gu",
   "avis": "Intéressant sur le papier, mais géographiquement le maillon le moins fluide du programme ce jour-là.",
   "when": "8 oct soir, seulement si énergie restante",
   "origin": "carnet",
   "lat": 37.5149363,
   "lng": 126.8947342
  },
  {
   "id": "seongsu-seoul-forest",
   "city": "seoul",
   "title": "Seongsu + Seoul Forest",
   "kr": "성수동 · 서울숲",
   "type": "Quartier + Parc · Plan B",
   "verdict": "option",
   "note": "Plan B si rien du K-Royal Festival n'attire le 9 octobre",
   "desc": "Quartier contemporain : boutiques, pop-ups, cafés K-beauty, petites rues, avec le Seoul Forest juste à côté pour respirer.",
   "zone": "Seongdong-gu",
   "avis": "Bonne option de repli si le programme du festival royal du 9 octobre ne sort rien de convaincant — journée contemporaine complète, park + shopping + cafés, sans réservation à prévoir.",
   "when": "9 oct — plan B seulement",
   "origin": "carnet",
   "lat": 37.5443878,
   "lng": 127.0374424
  },
  {
   "id": "saenggwabang",
   "city": "seoul",
   "title": "Saenggwabang",
   "kr": "생과방 · Pâtisserie et thé de cour",
   "type": "Expérience culturelle · Bonus",
   "verdict": "option",
   "note": "Bonus, pas colonne vertébrale — confirmé du 2 sept au 26 oct 2026",
   "desc": "Expérience de dégustation de pâtisseries et thé traditionnels de cour royale, dans un cadre historique.",
   "zone": "Palais royaux de Séoul (site à confirmer selon réservation)",
   "avis": "Sympa en complément si ça s'articule bien avec le reste du 9 octobre, mais clairement pas à construire toute une journée autour — c'est un bonus ponctuel, pas un point d'ancrage.",
   "when": "9 oct, si ça s'articule avec le reste",
   "origin": "carnet"
  },
  {
   "id": "dmz-tour",
   "city": "seoul",
   "title": "DMZ (Zone Démilitarisée)",
   "kr": "비무장지대 · Frontière Corée du Nord",
   "type": "Excursion · Journée complète",
   "verdict": "oui",
   "note": "Prend une journée entière — à faire remplacer un jour plus léger, pas à ajouter en plus",
   "desc": "Excursion vers la zone tampon entre les deux Corées, à 1h de Séoul.",
   "zone": "Paju, Gyeonggi-do (1h de Séoul) · départs 7h-8h30",
   "avis": "Rien à voir avec le reste du séjour — c'est LE moment le plus singulier géopolitiquement, et ça mérite clairement sa place.",
   "when": "Idéalement le 9 oct, en arbitrage avec le K-Royal Culture Festival — sinon un jour actuellement léger (27 sept matin possible mais risqué avant le vol Jeju)",
   "origin": "carnet",
   "lat": 37.8922482,
   "lng": 126.7430603
  },
  {
   "id": "spa-land-busan",
   "city": "busan",
   "title": "Spa Land Centum City",
   "kr": "스파랜드 · Plus grand jjimjilbang de Corée",
   "type": "Spa / Jjimjilbang · Détente",
   "verdict": "oui",
   "note": "Le plus grand jjimjilbang du pays — prévoir large, pas juste 1h",
   "desc": "Immense spa/sauna coréen sur 2 étages, intégré au Shinsegae Centum City (record Guinness du plus grand magasin du monde en surface).",
   "zone": "Haeundae-gu · 1F Shinsegae Mall, Centum City · station Centum City (ligne 2)",
   "avis": "C'est vraiment LA référence jjimjilbang en Corée — un cran au-dessus de ce qu'on trouve à Séoul selon plusieurs retours.",
   "when": "Séjour Busan (30 sept – 4 oct) · demi-journée, bien après une journée de marche",
   "origin": "carnet",
   "lat": 35.1682338,
   "lng": 129.1295279
  },
  {
   "id": "seogwipo-evening",
   "city": "jeju",
   "title": "Seogwipo (soirée d'arrivée)",
   "kr": "서귀포 · Centre-ville + marché + fontaine",
   "type": "Quartier · Balade nocturne",
   "verdict": "oui",
   "note": "Aucune course contre la montre — tout s'enchaîne naturellement à pied",
   "desc": "Découverte à pied du centre de Seogwipo : Lee Jung-seop Street et ses petites rues, le marché Seogwipo Maeil Olle, puis le port et Saeyeongyo.",
   "zone": "Seogwipo, centre-ville",
   "avis": "Bonne soirée d'arrivée sans enjeu : marcher, manger au marché, profiter du festival si les dates tombent bien, finir sur la fontaine.",
   "when": "27 sept, soir (arrivée à Jeju)",
   "origin": "carnet",
   "lat": 33.2494,
   "lng": 126.5603
  },
  {
   "id": "seongsan-ilchulbong",
   "city": "jeju",
   "title": "Seongsan Ilchulbong",
   "kr": "성산일출봉 · Pic volcanique UNESCO",
   "type": "Site UNESCO · Rando courte",
   "verdict": "oui",
   "note": "Pas besoin d'y aller au lever du soleil — se combine facilement avec Udo le même jour",
   "desc": "Cône volcanique classé UNESCO à la pointe est de Jeju.",
   "zone": "Est de Jeju, Seongsan-eup",
   "avis": "Contrairement à l'idée reçue, l'expérience sunrise n'est pas nécessaire pour apprécier le site — la montée elle-même (50 min) suffit et laisse largement le temps pour Udo dans la foulée.",
   "when": "28 sept, matin (avant Udo)",
   "origin": "carnet",
   "lat": 33.458056,
   "lng": 126.9425
  },
  {
   "id": "udo-velo",
   "city": "jeju",
   "title": "Udo à vélo",
   "kr": "우도 · Île à vélo",
   "type": "Île · Vélo · Priorité météo",
   "verdict": "oui",
   "note": "PRIORITÉ N°1 — à déplacer selon la météo, ne pas graver la date dans le marbre",
   "desc": "Petite île au large de Seongsan, environ 17 km de circonférence, se parcourt en vélo ou vélo électrique — c'est le moyen recommandé pour la couvrir.",
   "zone": "Au large de Seongsan (est de Jeju)",
   "avis": "LE moment fort du séjour Jeju selon moi — l'équivalent de votre expérience vélo autour du Fuji.",
   "when": "28 sept (ou 29 si meilleure météo — jour flexible selon vent/mer)",
   "origin": "carnet",
   "lat": 33.4728912,
   "lng": 126.9346052
  },
  {
   "id": "981-park-jeju",
   "city": "jeju",
   "title": "9.81 Park",
   "kr": "9.81 파크 · Gravity racing",
   "type": "Activité ludique · Parc",
   "verdict": "oui",
   "note": "Réserver une matinée précise, pas la journée entière",
   "desc": "Parc d'activités centré sur le 'gravity racing' : véhicules descendant une pente grâce à la seule gravité, avec chronométrage, data et vidéos de course.",
   "zone": "Jeju (ouest/centre)",
   "avis": "Franchement recommandé — mélange sport + jeu vidéo + culture coréenne assez unique en son genre.",
   "when": "29 sept, matin",
   "origin": "carnet",
   "lat": 33.3899391,
   "lng": 126.3663248
  },
  {
   "id": "aewol-coast-handam",
   "city": "jeju",
   "title": "Côte d'Aewol + Handam Coastal Trail",
   "kr": "애월 해안 · 한담해안산책로",
   "type": "Côte · Balade libre",
   "verdict": "oui",
   "note": "Improviser les arrêts plutôt que suivre une liste de spots",
   "desc": "Route côtière d'Aewol (~9 km) traversant ports, villages et portions volcaniques où on peut s'arrêter librement.",
   "zone": "Ouest de Jeju, Aewol-eup",
   "avis": "Parfait complément d'après-midi à 9.81 Park : pas de liste d'attractions à cocher, juste rouler le long de la côte et s'arrêter où l'envie prend — café, portion de sentier, vue sur la mer.",
   "when": "29 sept, après-midi (après 9.81 Park)",
   "origin": "carnet",
   "lat": 33.4591293,
   "lng": 126.3103796
  },
  {
   "id": "soesokkak",
   "city": "jeju",
   "title": "Soesokkak",
   "kr": "쇠소깍 · Gorge volcanique",
   "type": "Nature · Dernière matinée",
   "verdict": "oui",
   "note": "Bon plan si 2-3h disponibles avant le vol pour Busan — sinon zéro regret à sauter",
   "desc": "Gorge volcanique boisée où l'eau descendant du mont Hallasan rencontre la mer.",
   "zone": "Sud de Jeju, près de Seogwipo",
   "avis": "Bonne activité de dernière matinée avant le vol pour Busan : 1-2h suffisent, très 'Jeju' dans l'esprit sans nécessiter une grosse randonnée.",
   "when": "30 sept, matin (selon horaire du vol vers Busan)",
   "origin": "carnet",
   "lat": 33.2523471,
   "lng": 126.6238624
  },
  {
   "id": "saryeoni-forest",
   "city": "jeju",
   "title": "Saryeoni Forest",
   "kr": "사려니숲길 · Forêt de cèdres",
   "type": "Nature · Joker météo",
   "verdict": "option",
   "note": "Joker uniquement si Udo est annulé pour cause de météo — pas prioritaire sinon",
   "desc": "Grande promenade forestière à travers les cèdres, régulièrement citée dans les guides officiels de Jeju comme une des marches en forêt les plus agréables de l'île.",
   "zone": "Centre de Jeju",
   "avis": "Belle option, mais avec seulement deux journées complètes sur l'île, Udo et 9.81 Park restent plus distinctifs pour vous.",
   "when": "Uniquement en secours si Udo tombe à l'eau (météo)",
   "origin": "carnet",
   "lat": 33.3949678,
   "lng": 126.6839679
  },
  {
   "id": "manjanggul-cave",
   "city": "jeju",
   "title": "Manjanggul Cave",
   "kr": "만장굴 · Tunnel de lave UNESCO",
   "type": "Site UNESCO · Nature souterraine",
   "verdict": "oui",
   "note": "Rouvert en mai 2026 après 2,5 ans de travaux — proche de l'expo Ghibli, même secteur",
   "desc": "Tunnel de lave formé il y a 200 000-300 000 ans par l'éruption du Geomunoreum, l'un des plus grands au monde (7,4 km au total, dont environ 1 km ouvert au public en aller-retour depuis l'entrée n°2).",
   "zone": "Gujwa-eup, Jeju-si (est de l'île) — à proximité immédiate de l'expo Ghibli",
   "avis": "Bon timing : réouverture toute récente (mai 2026) avec passerelles neuves et éclairage LED refait, après 2 ans et demi de fermeture pour travaux de sécurité.",
   "when": "Séjour Jeju (27–30 sept) · à combiner avec Ghibli Exhibition et/ou Bijarim Forest (est de l'île)",
   "origin": "carnet",
   "lat": 33.5281972,
   "lng": 126.7717618
  },
  {
   "id": "hallasan",
   "city": "jeju",
   "title": "Mont Halla (Hallasan)",
   "kr": "한라산 · Plus haut sommet de Corée du Sud",
   "type": "Randonnée · Réservation obligatoire pour le sommet",
   "verdict": "option",
   "note": "Conflit réel avec le programme actuel — le sommet demande une journée entière que vous n'avez pas sur ce séjour",
   "desc": "Volcan bouclier culminant à 1 947 m, le plus haut sommet de Corée du Sud, avec le cratère Baengnokdam au sommet.",
   "zone": "Centre de l'île · plusieurs points de départ selon le sentier",
   "avis": "Soyons honnêtes sur le planning : un sommet (Seongpanak ou Gwaneumsa) prend 8-10h aller-retour avec transport, et votre séjour Jeju actuel (27-30 sept) est déjà occupé par Seongsan+Udo, 9.81 Park+Aewol, et Soesokkak avant le vol.",
   "when": "Nécessiterait de sacrifier une journée du programme actuel — à trancher si Hallasan est une priorité",
   "origin": "carnet",
   "lat": 33.3606281,
   "lng": 126.5358345
  },
  {
   "id": "haenyeo-show",
   "city": "jeju",
   "title": "Spectacle des Haenyeo",
   "kr": "해녀 · Plongeuses traditionnelles de Jeju",
   "type": "Culture vivante · Gratuit",
   "verdict": "oui",
   "note": "Gratuit, quotidien à 14h à Seongsan — mais ça entre en tension avec votre départ matinal vers Udo",
   "desc": "Les haenyeo sont les célèbres plongeuses de Jeju (souvent septuagénaires ou plus), qui pêchent en apnée jusqu'à 10m sans bouteille depuis des générations — tradition classée UNESCO en 2016, aujourd'hui en voie de disparition (moins de 3000 haenyeo actives).",
   "zone": "Plage au pied de Seongsan Ilchulbong (accès gratuit par le chemin de gauche, sans billet pour le pic)",
   "avis": "Un des rares moments authentiques et gratuits du séjour, mais il y a une vraie tension avec le plan actuel : vous êtes censés arriver à Seongsan vers 8h pour enchaîner avec Udo, alors que le spectacle est à 14h.",
   "when": "28 sept, 14h — à arbitrer avec le programme Seongsan/Udo déjà prévu ce jour-là",
   "origin": "carnet",
   "lat": 33.4571,
   "lng": 126.9403
  },
  {
   "id": "olle-trail-6",
   "city": "jeju",
   "title": "Olle Trail — section 6 (Soesokkak → Jeongbang → Seogwipo)",
   "kr": "올레길 6코스 · Portion recommandée",
   "type": "Rando côtière · Sentier balisé",
   "verdict": "oui",
   "note": "Ce tronçon relie deux lieux déjà dans votre carnet (Soesokkak et Seogwipo) — ne pas le traiter comme une activité à part",
   "desc": "L'Olle Trail est un réseau de 26 sentiers balisés faisant le tour de Jeju (437 km au total), inspiré du chemin de Compostelle.",
   "zone": "Sud de Jeju, entre Soesokkak et le centre de Seogwipo",
   "avis": "Plutôt que d'ajouter une randonnée séparée, le plus malin est de marcher la portion qui relie Soesokkak à Jeongbang Waterfall puis au centre de Seogwipo — vous avez déjà ces trois points dans votre programme à des moments différents.",
   "when": "30 sept matin (en prolongement naturel de Soesokkak) ou en portion libre selon l'envie",
   "origin": "carnet",
   "lat": 33.2478,
   "lng": 126.5975
  },
  {
   "id": "jeongbang-waterfall",
   "city": "jeju",
   "title": "Jeongbang Waterfall",
   "kr": "정방폭포 · Cascade tombant dans l'océan",
   "type": "Site naturel · Rapide",
   "verdict": "oui",
   "note": "La seule cascade d'Asie qui tombe directement dans la mer — à 15-20 min à pied du centre de Seogwipo",
   "desc": "Chute d'eau de 23 m de haut tombant directement dans l'océan — unique en son genre en Asie.",
   "zone": "Seogwipo, à 15-20 min à pied du centre (Chilsimni-ro)",
   "avis": "Vu la proximité immédiate avec votre point de chute à Seogwipo, c'est un ajout presque gratuit au programme — se glisse facilement dans la soirée d'arrivée du 27 sept ou en tout début de matinée avant de partir vers Seongsan.",
   "when": "27 sept, soir (arrivée) ou 28 sept, tôt le matin avant Seongsan",
   "origin": "carnet",
   "lat": 33.2448567,
   "lng": 126.5715794
  },
  {
   "id": "shooting-range-seoul",
   "city": "seoul",
   "title": "Stand de tir (arme réelle)",
   "kr": "실탄사격장 · Shooting range",
   "type": "Activité insolite · Adrénaline",
   "verdict": "oui",
   "note": "Vraies balles réelles, encadré par des tireurs pro — deux quartiers au choix",
   "desc": "Stands de tir à munitions réelles, une activité touristique assez populaire à Séoul (rare pays où c'est accessible aux visiteurs sans permis).",
   "zone": "Myeong-dong (Jung-gu) ou Gangnam/Songpa-gu (près de Lotte Tower)",
   "avis": "Activité 'on ne fait pas ça en France' assez fun et immersive, très orientée tourisme donc facile d'accès (staff multilingue, pas de permis nécessaire).",
   "when": "Plan soir ou après-midi flexible, l'un ou l'autre séjour à Séoul",
   "origin": "carnet",
   "lat": 37.5618609,
   "lng": 126.9865438
  },
  {
   "id": "cinema-premium-cgv",
   "city": "seoul",
   "title": "Cinéma premium (CGV Gold Class / Tempur)",
   "kr": "골드클래스 · Tempur Cinema · Sièges inclinables",
   "type": "Cinéma · Expérience insolite",
   "verdict": "oui",
   "note": "Deux niveaux de luxe existent — sofa inclinable (Gold Class) ou lit complet (Tempur Cinema)",
   "desc": "CJ CGV, la plus grande chaîne de cinémas coréenne, propose des salles premium bien au-delà du fauteuil classique.",
   "zone": "CGV Wangsimni (Gold Class) · CGV Yeouido IFC Mall (Tempur) · CGV Yongsan I'Park Mall (Tempur Cinema depuis janvier 2026)",
   "avis": "Une façon très coréenne de voir un film — l'expérience elle-même vaut presque plus que le film.",
   "when": "Soirée flexible, l'un ou l'autre séjour à Séoul — bon plan B jour de pluie",
   "origin": "carnet",
   "lat": 37.5253465,
   "lng": 126.9260431
  },
  {
   "id": "ferris-wheel-karaoke",
   "city": "seoul",
   "title": "Grande roue karaoké",
   "kr": "노래방 관람차 · Ferris wheel + karaoke",
   "type": "Activité insolite · À vérifier sur place",
   "verdict": "voir",
   "note": "Pas de landmark unique confirmé à 100% comme à Tokyo — à vérifier avant de compter dessus",
   "desc": "Concept né au Japon (le 'Big-O' de Tokyo Dome City, la référence du genre : cabines karaoké dans une grande roue, playlist internationale, 15 min de tour).",
   "zone": "Candidate la plus probable à Séoul : la grande roue de Lotte World (Magic Island, Jamsil)",
   "avis": "Honnêtement, je n'ai pas pu confirmer avec certitude que la roue de Lotte World a le karaoké embarqué — les sources que j'ai trouvées parlent d'une tendance générale coréenne plutôt que d'un lieu précis et confirmé.",
   "when": "À vérifier plus près de J-30 si l'idée tient toujours",
   "origin": "carnet",
   "lat": 37.5111158,
   "lng": 127.098167
  },
  {
   "id": "haeundae-dongbaekseom",
   "city": "busan",
   "title": "Haeundae + Dongbaekseom + Marine City",
   "kr": "해운대 · 동백섬 · 마린시티",
   "type": "Plage · Soirée d'arrivée",
   "verdict": "oui",
   "note": "Pas de réservation ce jour-là — le vol depuis Jeju ferait tout risquer",
   "desc": "Grande plage urbaine de Busan, bordée par les gratte-ciels de Marine City.",
   "zone": "Haeundae-gu",
   "avis": "Bonne introduction à Busan sans enjeu de réservation — logique après un vol depuis Jeju où un retard ferait tout basculer.",
   "when": "30 sept, arrivée en fin d'après-midi/soirée",
   "origin": "carnet",
   "lat": 35.1586975,
   "lng": 129.1603842
  },
  {
   "id": "busan-rock-festival",
   "city": "busan",
   "title": "Busan International Rock Festival",
   "kr": "부산국제록페스티벌 · 27e édition",
   "type": "Festival musique · Journée entière",
   "verdict": "oui",
   "note": "Dates, lieu et line-up confirmés — seul le timetable horaire jour par jour n'est pas encore publié",
   "desc": "Le plus ancien festival de rock international de Corée (27e édition en 2026), au Samnak Ecological Park (Sasang-gu).",
   "zone": "Samnak Ecological Park, Sasang-gu",
   "avis": "Bloquer la journée entière sans autre contrainte — pas la peine de caser Gamcheon le matin en pariant sur une heure d'arrivée au festival, tant que le timetable précis n'est pas publié : un artiste voulu pourrait très bien jouer tôt.",
   "when": "2 octobre, journée entière — réveil tranquille, pas d'autre activité prévue",
   "origin": "carnet",
   "lat": 35.1687484,
   "lng": 128.9735403
  },
  {
   "id": "gamcheon-culture-village",
   "city": "busan",
   "title": "Gamcheon Culture Village",
   "kr": "감천문화마을 · Village coloré en escaliers",
   "type": "Quartier · Architecture",
   "verdict": "oui",
   "note": "Prévoir 2h30-3h, pas juste la photo du Petit Prince",
   "desc": "Village en escaliers sur les collines de Busan, maisons colorées en cascade, ruelles étroites, art de rue et petites installations (dont la statue du Petit Prince, spot photo le plus connu).",
   "zone": "Saha-gu",
   "avis": "Même méthode qu'à Kyoto : axe touristique et points connus d'abord, puis ruelles latérales, escaliers, dérive.",
   "when": "3 octobre, 9h-12h",
   "origin": "carnet",
   "lat": 35.0973935,
   "lng": 129.0105921
  },
  {
   "id": "jagalchi-nampo",
   "city": "busan",
   "title": "Jagalchi + Nampo (marché et vieux quartier)",
   "kr": "자갈치시장 · 남포동 · BIFF 광장 · 국제시장",
   "type": "Marché · Street food · Quartier historique",
   "verdict": "oui",
   "note": "Ouvert 5h-22h sauf 1er/3e/5e mardis du mois — vérifier le calendrier",
   "desc": "Le plus grand marché aux poissons de Corée, puis enchaînement à pied vers BIFF Square (allée des étoiles du cinéma coréen) et Gukje Market (marché historique post-guerre de Corée), dans les ruelles de Nampo.",
   "zone": "Jung-gu, Nampo-dong",
   "avis": "Pas de checklist ici non plus : marcher Jagalchi → rues de poisson → BIFF Square → Gukje Market → ruelles de Nampo, et déjeuner sur place avec un plat vraiment busanais plutôt qu'un resto touristique.",
   "when": "3 octobre, 12h-16h30",
   "origin": "carnet",
   "lat": 35.0966339,
   "lng": 129.0307965
  },
  {
   "id": "gwangalli-drone-show",
   "city": "busan",
   "title": "Gwangalli + M Drone Light Show",
   "kr": "광안리 · 드론 라이트쇼",
   "type": "Plage · Spectacle nocturne",
   "verdict": "oui",
   "note": "Le spectacle du samedi est confirmé (19h/21h) — seul le thème précis du 3 octobre n'est pas encore publié",
   "desc": "Plage de Gwangalli, avec vue sur le pont Gwangan illuminé la nuit.",
   "zone": "Suyeong-gu",
   "avis": "Le 3 octobre 2026 tombe un samedi — bon timing.",
   "when": "3 octobre, 17h-21h (séance recommandée : 21h)",
   "origin": "carnet",
   "lat": 35.1531696,
   "lng": 129.118666
  },
  {
   "id": "sky-capsule-cheongsapo",
   "city": "busan",
   "title": "Sky Capsule Mipo → Cheongsapo",
   "kr": "스카이캡슐 · 미포-청사포",
   "type": "Transport touristique · Vue côtière",
   "verdict": "oui",
   "note": "Dernière matinée avant le départ pour Jeonju — horaires parfaits avec un vol/bus vers 14h",
   "desc": "Petite capsule suspendue sur rail longeant la côte entre Mipo (près de Haeundae) et Cheongsapo, environ 2 km en 30 minutes.",
   "zone": "Haeundae-gu, le long de la côte",
   "avis": "Partir de Mipo plutôt que l'inverse : c'est facile d'accès depuis Haeundae le matin, et on arrive progressivement face à la côte.",
   "when": "4 octobre, 8h30-11h30 (avant récupération des valises et départ vers 14h)",
   "origin": "carnet",
   "lat": 35.1613175,
   "lng": 129.1915668
  },
  {
   "id": "bulguksa",
   "city": "gyeongju",
   "title": "Bulguksa",
   "kr": "불국사 · Temple UNESCO",
   "type": "Temple · Premier arrêt",
   "verdict": "oui",
   "note": "1ère étape du programme, ~1h de route depuis Busan (départ 8h)",
   "desc": "Temple bouddhiste construit en 774 sous la dynastie Silla, chef-d'œuvre d'architecture et d'art religieux coréen.",
   "zone": "Est de Gyeongju, ~15 min du centre-ville",
   "avis": "Le point de départ logique du programme — mieux vaut y être tôt (le site est réputé calme entre 8h et 10h, avant l'arrivée des bus touristiques).",
   "when": "1er arrêt, ~8h-9h30 (après départ Busan 8h)",
   "origin": "carnet",
   "lat": 35.7898804,
   "lng": 129.3318909
  },
  {
   "id": "hwangridan-gil",
   "city": "gyeongju",
   "title": "Hwangridan-gil",
   "kr": "황리단길 · Rue tendance hanok",
   "type": "Quartier · Déjeuner",
   "verdict": "oui",
   "note": "2e étape — déjeuner vers 11h30-12h",
   "desc": "Rue commerçante tendance installée dans d'anciennes maisons hanok, mélangeant cafés design, boutiques et petits restaurants.",
   "zone": "Centre de Gyeongju, adjacent à Daereungwon",
   "avis": "Bon point de bascule dans la journée : après le calme religieux de Bulguksa, ambiance plus vivante et contemporaine pour le déjeuner.",
   "when": "11h30-12h, déjeuner",
   "origin": "carnet",
   "lat": 35.8376609,
   "lng": 129.209724
  },
  {
   "id": "daereungwon",
   "city": "gyeongju",
   "title": "Daereungwon",
   "kr": "대릉원 · Parc des tumuli royaux",
   "type": "Site historique · Tombeaux Silla",
   "verdict": "oui",
   "note": "3e étape, juste après le déjeuner à Hwangridan-gil",
   "desc": "Vaste parc verdoyant regroupant une vingtaine de tumuli (tombeaux royaux en forme de dôme herbeux) datant du royaume de Silla.",
   "zone": "Centre de Gyeongju, à côté de Hwangridan-gil",
   "avis": "Contraste saisissant avec le reste de la journée : ces collines herbeuses géométriques au milieu de la ville sont uniques à Gyeongju.",
   "when": "Après-midi, après le déjeuner",
   "origin": "carnet",
   "lat": 35.8381282,
   "lng": 129.2108206
  },
  {
   "id": "cheomseongdae",
   "city": "gyeongju",
   "title": "Cheomseongdae",
   "kr": "첨성대 · Observatoire astronomique",
   "type": "Site historique · Silla",
   "verdict": "oui",
   "note": "4e étape — courte visite, un des plus vieux observatoires d'Asie",
   "desc": "Tour de pierre du VIIe siècle, l'un des plus anciens observatoires astronomiques d'Asie encore debout.",
   "zone": "Centre de Gyeongju, à proximité de Daereungwon",
   "avis": "Visite rapide (15-20 min suffisent) mais incontournable de par sa signification historique — l'un des symboles les plus reconnaissables de Gyeongju.",
   "when": "Après-midi, entre Daereungwon et Gyelim",
   "origin": "carnet",
   "lat": 35.8347306,
   "lng": 129.2190014
  },
  {
   "id": "gyelim-wolseong",
   "city": "gyeongju",
   "title": "Gyelim + Wolseong",
   "kr": "계림 · 월성 · Forêt et site du palais Silla",
   "type": "Site historique · Nature",
   "verdict": "oui",
   "note": "5e étape — transition nature entre les sites de pierre",
   "desc": "Gyelim est une petite forêt sacrée liée à un mythe fondateur de la dynastie Silla (naissance du fondateur du clan Gyeongju Kim).",
   "zone": "Centre de Gyeongju, entre Cheomseongdae et Gyochon",
   "avis": "Bonne respiration verte dans une journée par ailleurs très dense en sites bâtis.",
   "when": "Après-midi, avant Gyochon",
   "origin": "carnet",
   "lat": 35.8322427,
   "lng": 129.2173376
  },
  {
   "id": "gyochon-village",
   "city": "gyeongju",
   "title": "Gyochon Hanok Village",
   "kr": "교촌마을 · Village traditionnel",
   "type": "Village · Artisanat / gastronomie",
   "verdict": "oui",
   "note": "6e étape — bon moment pour une pause thé/vin de riz avant Woljeonggyo",
   "desc": "Village traditionnel de maisons hanok, connu pour son artisanat local et surtout le gyeongju beopju, un vin de riz traditionnel brassé dans le village depuis des générations selon une recette familiale.",
   "zone": "Sud du centre de Gyeongju, à côté de Wolseong",
   "avis": "Bon moment pour ralentir avant la dernière ligne droite de la journée — déguster le beopju local est une expérience assez unique à ce village précis.",
   "when": "Fin d'après-midi, avant Woljeonggyo",
   "origin": "carnet",
   "lat": 35.8295398,
   "lng": 129.2148298
  },
  {
   "id": "woljeonggyo",
   "city": "gyeongju",
   "title": "Woljeonggyo",
   "kr": "월정교 · Pont Silla reconstruit",
   "type": "Pont historique · Illumination nocturne",
   "verdict": "oui",
   "note": "7e étape — vers la fin de journée, magique une fois éclairé",
   "desc": "Pont en bois de style Silla, reconstitution moderne d'un pont historique traversant la rivière Namcheon.",
   "zone": "Sud du centre de Gyeongju, à côté de Gyochon",
   "avis": "Timing parfait en fin de journée pour capter la transition jour/nuit et voir le pont s'illuminer progressivement — un des visuels les plus marquants de Gyeongju.",
   "when": "Fin de journée, coucher de soleil/tombée de la nuit",
   "origin": "carnet",
   "lat": 35.8291928,
   "lng": 129.2181213
  },
  {
   "id": "donggung-wolji-night",
   "city": "gyeongju",
   "title": "Donggung & Wolji de nuit",
   "kr": "동궁과 월지 · Anapji · Palais illuminé",
   "type": "Palais · Illumination nocturne",
   "verdict": "oui",
   "note": "Dernière étape avant le retour à Busan — LE moment fort de la journée selon plusieurs guides",
   "desc": "Ancien palais secondaire et jardin du royaume de Silla, autrefois utilisé pour recevoir des invités importants et célébrer des événements.",
   "zone": "Centre de Gyeongju",
   "avis": "Plusieurs guides désignent ce site comme LE incontournable nocturne de Gyeongju — l'illumination des pavillons sur l'eau est réellement spectaculaire et différente de tout ce que vous aurez vu dans la journée.",
   "when": "Soirée, après le dîner — dernière étape avant le retour à Busan",
   "origin": "carnet",
   "lat": 35.8348173,
   "lng": 129.2265645
  },
  {
   "id": "jeonju-hanok-village",
   "city": "jeonju",
   "title": "Jeonju Hanok Village",
   "kr": "전주한옥마을 · Plus grand village hanok de Corée",
   "type": "Quartier · À vivre 2 fois, 2 ambiances",
   "verdict": "oui",
   "note": "Visité 2 fois dans votre programme : balade nocturne le 4, puis errance libre le 5 — deux ambiances différentes, aucune redondance",
   "desc": "Le plus grand village de maisons traditionnelles hanok de Corée, avec plus de 800 structures.",
   "zone": "Wansan-gu, cœur de Jeonju",
   "avis": "L'astuce, c'est de le vivre deux fois différemment comme prévu : de nuit à l'arrivée (ambiance calme, rues vides, lumières) puis en errance libre de jour (rues vivantes, visiteurs en hanbok, lumière sur les toits).",
   "when": "4 oct soir (balade nocturne) + 5 oct journée (errance libre, sans itinéraire strict)",
   "origin": "carnet",
   "lat": 35.8175376,
   "lng": 127.1520417
  },
  {
   "id": "jeonjucheon",
   "city": "jeonju",
   "title": "Jeonjucheon",
   "kr": "전주천 · Rivière traversant la ville",
   "type": "Rivière · Balade",
   "verdict": "oui",
   "note": "Bon fil conducteur pour la balade nocturne d'arrivée",
   "desc": "Rivière traversant Jeonju, bordée de chemins piétons agréables pour une balade tranquille, avec des passages à gué en pierre à certains endroits.",
   "zone": "Traverse le centre de Jeonju, à proximité du Hanok Village",
   "avis": "Bon complément à la balade nocturne du Hanok Village — la rivière donne un axe naturel à suivre sans avoir à structurer l'itinéraire.",
   "when": "4 oct, soir (avec le Hanok Village)",
   "origin": "carnet",
   "lat": 35.8107118,
   "lng": 127.1533442
  },
  {
   "id": "omokdae",
   "city": "jeonju",
   "title": "Omokdae + Imokdae",
   "kr": "오목대 · 이목대 · Pavillons panoramiques",
   "type": "Point de vue · Histoire",
   "verdict": "oui",
   "note": "Passage obligé vers Jaman — ne pas s'arrêter juste à la vue",
   "desc": "Pavillons au sommet de la colline la plus haute de Jeonju, site où Yi Seong-gye (futur fondateur de la dynastie Joseon) aurait célébré une victoire militaire.",
   "zone": "En hauteur, juste au-dessus du Hanok Village",
   "avis": "Idéalement situé sur le chemin vers Jaman Mural Village — depuis les pavillons, traverser le pont Omokgyo puis suivre le panneau indicateur, environ 10 min de marche au total.",
   "when": "5 oct, en passant vers Jaman",
   "origin": "carnet",
   "lat": 35.814387,
   "lng": 127.154601
  },
  {
   "id": "jaman-mural-village",
   "city": "jeonju",
   "title": "Jaman Mural Village",
   "kr": "자만벽화마을 · Village de fresques",
   "type": "Quartier · Street art",
   "verdict": "oui",
   "note": "Montée raide mais courte (~10 min depuis le Hanok Village) — moins fréquenté que Gamcheon à Busan",
   "desc": "Quartier résidentiel à flanc de colline entièrement recouvert de fresques murales mêlant références coréennes et internationales : personnages Studio Ghibli, Beatles, Adventure Time, et créations locales.",
   "zone": "Sur la colline au-dessus du Hanok Village, via Omokdae",
   "avis": "Ambiance plus intime et moins touristique que Gamcheon Culture Village à Busan — la montée est raide mais courte, largement compensée par les fresques et la vue depuis le haut.",
   "when": "5 oct, matin (via Omokdae)",
   "origin": "carnet",
   "lat": 35.8142152,
   "lng": 127.1572118
  },
  {
   "id": "nambu-market",
   "city": "jeonju",
   "title": "Nambu Market",
   "kr": "남부시장 · Marché traditionnel + food court jeune",
   "type": "Marché · Street food",
   "verdict": "oui",
   "note": "Deux étages, deux ambiances : marché traditionnel en bas, food court contemporain en haut",
   "desc": "Marché traditionnel principal de Jeonju, à 10 min à pied au sud du Hanok Village.",
   "zone": "10 min à pied au sud du Hanok Village",
   "avis": "Le contraste entre les deux étages résume bien l'esprit de la ville : tradition au rez-de-chaussée, réinvention créative à l'étage.",
   "when": "5 oct, après-midi (dans la continuité de la balade)",
   "origin": "carnet",
   "lat": 35.8126868,
   "lng": 127.1468566
  },
  {
   "id": "gaekridan-gil",
   "city": "jeonju",
   "title": "Gaekridan-gil",
   "kr": "객리단길 · Rue tendance moderne",
   "type": "Quartier · Cafés / boutiques",
   "verdict": "oui",
   "note": "Contraste volontaire avec le Hanok Village — Jeonju version contemporaine",
   "desc": "Rue commerçante tendance dans le centre-ville de Jeonju, mélange de cafés design, boutiques indépendantes et petits restaurants — l'équivalent local des rues type Gaeksa-gil ou Hongdae, dans une version plus à taille humaine.",
   "zone": "Centre-ville de Jeonju, en dehors du Hanok Village",
   "avis": "Bonne façon de terminer la journée du 5 sur une note différente : après une journée très patrimoine/nature (Hanok Village, Omokdae, Jaman, rivière, Nambu Market), Gaekridan-gil montre la Jeonju contemporaine avant une soirée libre.",
   "when": "5 oct, fin d'après-midi/soirée libre",
   "origin": "carnet",
   "lat": 35.8200343,
   "lng": 127.1398344
  },
  {
   "id": "jeonju-hyanggyo",
   "city": "jeonju",
   "title": "Jeonju Hyanggyo",
   "kr": "전주향교 · École confucéenne",
   "type": "Site historique · Calme",
   "verdict": "oui",
   "note": "FERMÉ LE LUNDI — sans incidence ici puisque prévu le mardi 6",
   "desc": "Ancienne école confucéenne de la dynastie Joseon, utilisée pour les rites ancestraux et l'enseignement.",
   "zone": "Sud du Hanok Village",
   "avis": "Bon point de départ calme pour la matinée du départ — moins fréquenté que Gyeonggijeon, et le ginkgo commence à peine à tourner début octobre.",
   "when": "6 oct, matin (1ère étape avant le départ)",
   "origin": "carnet",
   "lat": 35.8126194,
   "lng": 127.1572279
  },
  {
   "id": "gyeonggijeon",
   "city": "jeonju",
   "title": "Gyeonggijeon",
   "kr": "경기전 · Sanctuaire du portrait royal",
   "type": "Sanctuaire · Photo hanbok",
   "verdict": "oui",
   "note": "Meilleur endroit pour la photo hanbok — moins de foule qu'à Gyeongbokgung à Séoul",
   "desc": "Sanctuaire abritant le portrait officiel du roi Taejo, fondateur de la dynastie Joseon.",
   "zone": "Cœur du Hanok Village",
   "avis": "Si l'envie de louer un hanbok pour une photo n'a pas encore été assouvie à Séoul (Insadong), c'est ici que ça vaut le plus le coup selon plusieurs retours de visiteurs — nettement moins de foule qu'à Gyeongbokgung.",
   "when": "6 oct, matin (après Hyanggyo, avant le déjeuner)",
   "origin": "carnet",
   "lat": 35.8153492,
   "lng": 127.1497938
  },
  {
   "id": "atelier-artisanat-jeonju",
   "city": "jeonju",
   "title": "Atelier d'artisanat (hanji / poterie / laque)",
   "kr": "공예 체험 · Atelier traditionnel",
   "type": "Atelier · Optionnel",
   "verdict": "option",
   "note": "À caser seulement si le timing du dernier matin le permet avant le déjeuner et le départ",
   "desc": "Jeonju est réputée pour le hanji, papier traditionnel coréen fabriqué à partir d'écorce de mûrier (un musée du Hanji existe en ville).",
   "zone": "Ruelles entre Gyeonggijeon et Omokdae",
   "avis": "Sympa en complément si le programme du dernier matin (Hyanggyo → Gyeonggijeon) laisse assez de marge avant le déjeuner et le départ pour Séoul — mais clairement le premier élément à sacrifier si le timing se resserre, vu que c'est le jour du départ.",
   "when": "6 oct, en option avant le déjeuner — seulement si le timing le permet",
   "origin": "carnet"
  },
  {
   "id": "jamsu-bridge-festival",
   "city": "seoul",
   "title": "Car-Free Jamsu Bridge Festival",
   "kr": "잠수교 차 없는 다리 축제 · Festival du Han River",
   "type": "Festival · Dimanche uniquement",
   "verdict": "option",
   "note": "AUCUN de tes jours à Séoul ne tombe un dimanche — conflit de calendrier réel, pas juste théorique",
   "desc": "Le Jamsu Bridge (pont inférieur du Banpo Bridge) est fermé aux voitures chaque dimanche et transformé en espace piéton géant sur 1,1 km : food trucks, marché artisanal, marché de producteurs locaux, spectacles de rue, silent disco, zones photo LED.",
   "zone": "Jamsu Bridge / Banpo Hangang Park, entre Gangnam et Yongsan",
   "avis": "J'ai vérifié précisément : tes deux séjours à Séoul sont 24-27 sept (jeu-dim) et 6-10 oct (mar-sam).",
   "when": "27 sept en théorie — à vérifier selon l'heure du vol vers Jeju, sinon aucun créneau réaliste",
   "origin": "carnet",
   "lat": 37.5165,
   "lng": 126.9955
  }
 ]
};
